# Generated by Django 6.0.3 on 2026-03-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_project_name'),
        ('tracker', '0003_event_resolved'),
    ]

    operations = [
    ]
