# Generated by Django 6.0.3 on 2026-03-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_merge_0003_alter_project_name_0003_event_resolved'),
        ('tracker', '0004_owner'),
    ]

    operations = [
    ]
