# Generated by Django 6.0.3 on 2026-03-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_merge_20260307_0736'),
        ('tracker', '0005_milestone_dates'),
    ]

    operations = [
    ]
