# Generated by Django 6.0.3 on 2026-03-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_merge_0005_merge_20260307_0736_0005_milestone_dates'),
        ('tracker', '0006_user_ownership'),
    ]

    operations = [
    ]
