# Generated by Django 6.0.3 on 2026-03-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_merge_20260311_1843'),
        ('tracker', '0007_project_settings_fields'),
    ]

    operations = [
    ]
