# Generated by Django 6.0.3 on 2026-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_merge_20260311_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(blank=True, help_text='Target / due date', null=True),
        ),
    ]
