# Generated by Django 6.0.3 on 2026-03-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_oauth'),
        ('tracker', '0009_alter_milestone_date'),
    ]

    operations = [
    ]
